name: Run Unit and E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2


      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Ou a versão que seu projeto utiliza


      - name: Install dependencies
        run: npm install


      - name: Run Unit Tests
        run: npm run test:unit


      - name: Run Cypress E2E Tests
        run: npm run test:e2e


      - name: Generate Coverage Report
        run: npm run test:unit -- --coverage
